openapi: "3.0.0"
info:
  title: Simple API overview
  version: 2.0.0
paths:
  /hello:
    get:
      operationId: listVersionsv2
      summary: List API versions
      responses:
        '200':
          description: |-
            200 response
